# Man vs Machine on Oslo Bors - Data

In [45]:
import pandas as pd
import numpy as np
import pyreadr
import warnings
warnings.filterwarnings('ignore')

### 1. Data cleaning / engineering

In [46]:
# load the data
equity_df = pd.read_csv('../Data/master_equity_panel_1980_2024.csv', encoding='latin1')

# rename the first column and drop the last column
#equity_df.rename(columns={equity_df.columns[0]: 'TradeDate'}, inplace=True)
#equity_df.drop(columns=equity_df.columns[-1], inplace=True)

equity_df

,TradeDate,ISIN,SecurityType,Generic,SharesIssued,OffShareTurnover,ReturnGeneric,ReturnAdjGeneric
0,1996-07-31,ANN7425Q1095,Ordinary Shares,67.0,67456832.0,676666.0,-0.049645,-0.049645
1,1996-08-31,ANN7425Q1095,Ordinary Shares,63.0,67456832.0,1158850.0,-0.059701,-0.059701
2,1996-09-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,773118.0,0.047619,0.047619
3,1996-10-31,ANN7425Q1095,Ordinary Shares,61.5,67456832.0,1211000.0,-0.068182,-0.068182
4,1996-11-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,1036673.0,0.073171,0.073171
...,...,...,...,...,...,...,...,...
172639,2007-09-30,VGG3724W1014,Ordinary Shares,38.0,21500000.0,68200.0,-0.037975,-0.037975
172640,2007-10-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6301274.0,1.157895,1.157895
172641,2007-11-30,VGG3724W1014,Ordinary Shares,82.0,21500000.0,1066200.0,0.000000,0.000000
172642,2007-12-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6800.0,0.000000,0.000000
172643,1995-10-31,XL0003000391,Warrant - Tegningsrett,5.0,0.0,1619790.0,0.086957,0.086957

In [47]:
# standardize ISIN codes
equity_df['ISIN'] = equity_df['ISIN'].str.upper().str.strip()

# align the monthly dates to the end of the month
equity_df['TradeDate'] = pd.to_datetime(equity_df['TradeDate'], errors='coerce') + pd.offsets.MonthEnd(0)

equity_df

,TradeDate,ISIN,SecurityType,Generic,SharesIssued,OffShareTurnover,ReturnGeneric,ReturnAdjGeneric
0,1996-07-31,ANN7425Q1095,Ordinary Shares,67.0,67456832.0,676666.0,-0.049645,-0.049645
1,1996-08-31,ANN7425Q1095,Ordinary Shares,63.0,67456832.0,1158850.0,-0.059701,-0.059701
2,1996-09-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,773118.0,0.047619,0.047619
3,1996-10-31,ANN7425Q1095,Ordinary Shares,61.5,67456832.0,1211000.0,-0.068182,-0.068182
4,1996-11-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,1036673.0,0.073171,0.073171
...,...,...,...,...,...,...,...,...
172639,2007-09-30,VGG3724W1014,Ordinary Shares,38.0,21500000.0,68200.0,-0.037975,-0.037975
172640,2007-10-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6301274.0,1.157895,1.157895
172641,2007-11-30,VGG3724W1014,Ordinary Shares,82.0,21500000.0,1066200.0,0.000000,0.000000
172642,2007-12-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6800.0,0.000000,0.000000
172643,1995-10-31,XL0003000391,Warrant - Tegningsrett,5.0,0.0,1619790.0,0.086957,0.086957

In [48]:
# check the security types
print(equity_df['SecurityType'].unique())

# check the distribution of the security types
print(equity_df['SecurityType'].value_counts())

['Ordinary Shares' 'Warrant - Tegningsrett' 'Other' 'New Shares'
 'A Shares' 'B Shares' 'Exchange traded funds' 'Free Shares'
 'Converted Shares' 'Preference Shares' 'New B Shares'
 'Converted F Shares' 'Converted B Shares' 'Converted A Shares'
 'Primary Capital Certificates' 'Converted Primary Capital Certificates'
 'Warrant - European Call' 'Warrant - European Put'
 'Warrant - Index Warrant' 'Warrant - American Call'
 'Warrant - Exchange tradable notes' 'Warrant - Bull ETN'
 'Warrant - Bear ETN']
SecurityType
Ordinary Shares                           95900
Warrant - European Call                   22027
Other                                     18290
Warrant - European Put                     7831
Primary Capital Certificates               5949
Warrant - Bull ETN                         5053
Warrant - Bear ETN                         5038
B Shares                                   4219
A Shares                                   3513
Warrant - Exchange tradable notes          1781
Exchange traded funds                      1162
Warrant - Tegningsrett                      784
Free Shares                                 696
Preference Shares                           154
New Shares                                  125
Warrant - Index Warrant                      52
Converted Shares                             35
Warrant - American Call                      14
New B Shares                                 12
Converted B Shares                            4
Converted A Shares                            3
Converted Primary Capital Certificates        1
Converted F Shares                            1
Name: count, dtype: int64

In [49]:
# define the relevant equity types
keep_types = [
    'Ordinary Shares', 'A Shares', 'B Shares', 'Free Shares', 
    'Primary Capital Certificates', 'Converted Shares', 'Preference Shares'
]

# filter the DataFrame to keep only the relevant equity types
equity_df = equity_df[equity_df['SecurityType'].isin(keep_types)]

print(equity_df['SecurityType'].unique())

['Ordinary Shares' 'A Shares' 'B Shares' 'Free Shares' 'Converted Shares'
 'Preference Shares' 'Primary Capital Certificates']

In [50]:
# find the last date for each ISIN
last_dates = equity_df.groupby('ISIN')['TradeDate'].max().reset_index()

# merge the last dates back to the original DataFrame
equity_df = pd.merge(equity_df, last_dates, on='ISIN', suffixes=('', '_Last'))

# see the distribution of the last dates
equity_df.groupby('ISIN')['TradeDate_Last'].first().value_counts().sort_index()

TradeDate_Last
1985-03-31      1
1985-09-30      1
1986-03-31      2
1986-04-30      2
1986-05-31      3
             ...
2024-09-30      2
2024-10-31      3
2024-11-30      6
2024-12-31      3
2025-01-31    322
Name: count, Length: 342, dtype: int64

In [51]:
# sort by ISIN and TradeDate
equity_df_sorted = equity_df.sort_values(by=['ISIN', 'TradeDate'])

# calculate the difference in TradeDate for each ISIN
equity_df_sorted['TradeDate_Diff'] = equity_df_sorted.groupby('ISIN')['TradeDate'].diff()

In [52]:
# flag the row where with the last date before the gap as delisted
equity_df_sorted['Delisted'] = False

# flag the last observation before a gap (>32 days) within each ISIN
gap_after = equity_df_sorted.groupby('ISIN')['TradeDate_Diff'].shift(-1) > pd.Timedelta(days=32)
equity_df_sorted.loc[gap_after.fillna(False), 'Delisted'] = True

equity_df_sorted

,TradeDate,ISIN,SecurityType,Generic,SharesIssued,OffShareTurnover,ReturnGeneric,ReturnAdjGeneric,TradeDate_Last,TradeDate_Diff,Delisted
0,1996-07-31,ANN7425Q1095,Ordinary Shares,67.0,67456832.0,676666.0,-0.049645,-0.049645,1997-01-31,NaT,False
1,1996-08-31,ANN7425Q1095,Ordinary Shares,63.0,67456832.0,1158850.0,-0.059701,-0.059701,1997-01-31,31 days,False
2,1996-09-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,773118.0,0.047619,0.047619,1997-01-31,30 days,False
3,1996-10-31,ANN7425Q1095,Ordinary Shares,61.5,67456832.0,1211000.0,-0.068182,-0.068182,1997-01-31,31 days,False
4,1996-11-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,1036673.0,0.073171,0.073171,1997-01-31,30 days,False
...,...,...,...,...,...,...,...,...,...,...,...
110461,2007-08-31,VGG3724W1014,Ordinary Shares,39.5,21500000.0,619200.0,-0.141304,-0.141304,2007-12-31,31 days,False
110462,2007-09-30,VGG3724W1014,Ordinary Shares,38.0,21500000.0,68200.0,-0.037975,-0.037975,2007-12-31,30 days,False
110463,2007-10-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6301274.0,1.157895,1.157895,2007-12-31,31 days,False
110464,2007-11-30,VGG3724W1014,Ordinary Shares,82.0,21500000.0,1066200.0,0.000000,0.000000,2007-12-31,30 days,False
110465,2007-12-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6800.0,0.000000,0.000000,2007-12-31,31 days,False

In [53]:
# flag bankrupcy or m&a delisting for last dates of each isin
latest_date = equity_df_sorted['TradeDate'].max()

# only consider the terminal row per ISIN, excluding ISINs that are alive at dataset end
eligible_last_row = (
    equity_df_sorted['TradeDate'].eq(equity_df_sorted['TradeDate_Last']) &
    equity_df_sorted['TradeDate_Last'].ne(latest_date)
)

ma_mask = eligible_last_row & equity_df_sorted['ReturnGeneric'].ge(-0.5)
bankruptcy_mask = eligible_last_row & ~equity_df_sorted['ReturnGeneric'].ge(-0.5)

equity_df_sorted['Delisted_Bankruptcy_MA'] = False
equity_df_sorted['Delist_Type'] = np.nan

equity_df_sorted.loc[ma_mask | bankruptcy_mask, 'Delisted_Bankruptcy_MA'] = True
equity_df_sorted.loc[ma_mask, 'Delist_Type'] = 'M&A'
equity_df_sorted.loc[bankruptcy_mask, 'Delist_Type'] = 'Bankruptcy'

# if bankruptcy and missing ReturnGeneric, impute as requested
equity_df_sorted.loc[bankruptcy_mask & equity_df_sorted['ReturnGeneric'].isna(), 'ReturnGeneric'] = -0.9

In [54]:
# count the number of M&A and bankruptcy delistings
delist_counts = equity_df_sorted['Delist_Type'].value_counts()
print(delist_counts)

# count the number of bankruptcy delistings with imputed ReturnGeneric
imputed_bankruptcy_count = equity_df_sorted[(equity_df_sorted['Delist_Type'] == 'Bankruptcy') & (equity_df_sorted['ReturnGeneric'] == -0.9)].shape[0]
print(f"Number of bankruptcy delistings with imputed ReturnGeneric: {imputed_bankruptcy_count}")

Delist_Type
M&A           743
Bankruptcy     26
Name: count, dtype: int64
Number of bankruptcy delistings with imputed ReturnGeneric: 17

In [55]:
# set spell id for each ISIN
equity_df_sorted['SpellID'] = equity_df_sorted.groupby('ISIN')['TradeDate_Diff'].apply(
    lambda x: (x > pd.Timedelta(days=32)).cumsum() + 1
).values

equity_df_sorted

,TradeDate,ISIN,SecurityType,Generic,SharesIssued,OffShareTurnover,ReturnGeneric,ReturnAdjGeneric,TradeDate_Last,TradeDate_Diff,Delisted,Delisted_Bankruptcy_MA,Delist_Type,SpellID
0,1996-07-31,ANN7425Q1095,Ordinary Shares,67.0,67456832.0,676666.0,-0.049645,-0.049645,1997-01-31,NaT,False,False,NaN,1
1,1996-08-31,ANN7425Q1095,Ordinary Shares,63.0,67456832.0,1158850.0,-0.059701,-0.059701,1997-01-31,31 days,False,False,NaN,1
2,1996-09-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,773118.0,0.047619,0.047619,1997-01-31,30 days,False,False,NaN,1
3,1996-10-31,ANN7425Q1095,Ordinary Shares,61.5,67456832.0,1211000.0,-0.068182,-0.068182,1997-01-31,31 days,False,False,NaN,1
4,1996-11-30,ANN7425Q1095,Ordinary Shares,66.0,67456832.0,1036673.0,0.073171,0.073171,1997-01-31,30 days,False,False,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110461,2007-08-31,VGG3724W1014,Ordinary Shares,39.5,21500000.0,619200.0,-0.141304,-0.141304,2007-12-31,31 days,False,False,NaN,1
110462,2007-09-30,VGG3724W1014,Ordinary Shares,38.0,21500000.0,68200.0,-0.037975,-0.037975,2007-12-31,30 days,False,False,NaN,1
110463,2007-10-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6301274.0,1.157895,1.157895,2007-12-31,31 days,False,False,NaN,1
110464,2007-11-30,VGG3724W1014,Ordinary Shares,82.0,21500000.0,1066200.0,0.000000,0.000000,2007-12-31,30 days,False,False,NaN,1
110465,2007-12-31,VGG3724W1014,Ordinary Shares,82.0,21500000.0,6800.0,0.000000,0.000000,2007-12-31,31 days,False,True,M&A,1

In [56]:
# save the final DataFrame to a new CSV file
equity_df_sorted.to_csv('../Data/processed_equity_data.csv', index=False)

### 2. Feature engineering

In [57]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize

# Assuming your dataframe is named 'df'
equity_df_sorted['TradeDate'] = pd.to_datetime(equity_df_sorted['TradeDate'])

# Ensure strict sorting before calculating rolling features
equity_df_sorted.sort_values(by=['ISIN', 'SpellID', 'TradeDate'], inplace=True)

# -------------------------------------------------------------------
# 1. WINSORIZE TARGET (Cap at 1st and 99th Percentile)
# -------------------------------------------------------------------
# This neutralizes the +59,300% anomalies.
lower_bound = equity_df_sorted['ReturnAdjGeneric'].quantile(0.01)
upper_bound = equity_df_sorted['ReturnAdjGeneric'].quantile(0.99)
equity_df_sorted['ReturnAdjGeneric_win'] = equity_df_sorted['ReturnAdjGeneric'].clip(lower=lower_bound, upper=upper_bound)

# Create the Target by shifting the already-winsorized return
equity_df_sorted['Target'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric_win'].shift(-1)

# Create a non-winsorized target for comparison (optional)
equity_df_sorted['Target_raw'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric'].shift(-1)

# -------------------------------------------------------------------
# 2. SIZE & LIQUIDITY FEATURES
# -------------------------------------------------------------------
# Market Cap = Price (Generic) * SharesIssued
equity_df_sorted['mkt_cap'] = equity_df_sorted['Generic'] * equity_df_sorted['SharesIssued']
# Log Size normalizes the exponential difference between micro-caps and Equinor
equity_df_sorted['log_size'] = np.log(equity_df_sorted['mkt_cap'].replace(0, np.nan))

# Turnover = Shares Traded / Total Shares Issued (proxy for liquidity)
# Using 'OffShareTurnover' or 'NonOffShareTurnover' depending on your preference
equity_df_sorted['turnover'] = equity_df_sorted['OffShareTurnover'] / equity_df_sorted['SharesIssued']

# -------------------------------------------------------------------
# 3. MOMENTUM & REVERSAL (Spell-Aware)
# -------------------------------------------------------------------
# Short-term Reversal: The return of the most recent month (t-1)
equity_df_sorted['rev_1m'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric_win'].shift(1)

# Intermediate Momentum (6m and 12m):
# Standard finance literature skips the most recent month (t-1) to isolate momentum from reversal.
# We shift(2) to start from t-2, then sum the previous 5 or 11 months.
equity_df_sorted['mom_6m'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric_win'].transform(
    lambda x: x.shift(2).rolling(5).sum()
)

equity_df_sorted['mom_12m'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric_win'].transform(
    lambda x: x.shift(2).rolling(11).sum()
)

# -------------------------------------------------------------------
# 4. RISK METRICS (Volatility)
# -------------------------------------------------------------------
# 3-Month and 6-Month Realized Volatility
equity_df_sorted['vol_3m'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric_win'].transform(
    lambda x: x.shift(1).rolling(3).std()
)
equity_df_sorted['vol_6m'] = equity_df_sorted.groupby(['ISIN', 'SpellID'])['ReturnAdjGeneric_win'].transform(
    lambda x: x.shift(1).rolling(6).std()
)


print("Factor Zoo successfully created!")

Factor Zoo successfully created!

In [58]:
# 1. Calculate the absolute NOK value traded that month
# Generic (Price) * OffShareTurnover (Shares Traded)
equity_df_sorted['NOK_volume'] = equity_df_sorted['Generic'] * equity_df_sorted['OffShareTurnover']

# 2. Cross-sectionally rank the NOK volume each month
equity_df_sorted['liquidity_rank'] = equity_df_sorted.groupby('TradeDate')['NOK_volume'].rank(pct=True)

# 3. Drop the most illiquid/un-tradable bottom 20% of the market
investable_universe = equity_df_sorted[equity_df_sorted['liquidity_rank'] >= 0.10].copy()

In [59]:
# 1. Define the list of raw features you just created
features_to_rank = [
    'log_size', 'turnover', 
    'rev_1m', 'mom_6m', 'mom_12m', 
    'vol_3m', 'vol_6m'
]

# 2. Loop through each feature and create a new ranked column
for col in features_to_rank:
    # rank(pct=True) gives a value from 0.0 to 1.0 within each month
    investable_universe[f'{col}_rank'] = investable_universe.groupby('TradeDate')[col].rank(pct=True)

# 3. Drop the rows that have NaNs in the ranked features
# This automatically removes the first 5-11 months of new spells where 
# rolling features like mom_12m couldn't be calculated.
ranked_cols = [f'{col}_rank' for col in features_to_rank]
investable_universe = investable_universe.dropna(subset=ranked_cols)

# Optional: You can drop the raw feature columns now to save memory, 
# as the ML model will ONLY use the ranked versions.
# investable_universe = investable_universe.drop(columns=features_to_rank)

In [60]:
# -------------------------------------------------------------------
# 5. CROSS-SECTIONAL Z-SCORING - *ADDED*
# -------------------------------------------------------------------
features_to_zscore = ['log_size', 'turnover', 'rev_1m', 'mom_6m', 'mom_12m', 'vol_3m', 'vol_6m', 'Target']

def cs_zscore(df, col):
    # (Value - Mean) / Standard Deviation, grouped by TradeDate
    return df.groupby('TradeDate')[col].transform(lambda x: (x - x.mean()) / x.std())

for col in features_to_zscore:
    investable_universe[f'{col}_z'] = cs_zscore(investable_universe, col)


# -------------------------------------------------------------------
# 6. DROP NaNs (End of pipeline)
# -------------------------------------------------------------------
# Drop the missing targets at the end of the spells
investable_universe = investable_universe.dropna(subset=['Target', 'Target_raw'])

# Drop rows missing the longest rolling feature (first 11 months of new spells)
investable_universe = investable_universe.dropna(subset=['mom_12m_z'])

print("Factor Zoo perfectly created and ready for ML!")

Factor Zoo perfectly created and ready for ML!

In [61]:
# save the final DataFrame to a new CSV file
investable_universe.to_csv('../Data/investable_universe.csv', index=False)

In [62]:
investable_universe

,TradeDate,ISIN,SecurityType,Generic,SharesIssued,OffShareTurnover,ReturnGeneric,ReturnAdjGeneric,TradeDate_Last,TradeDate_Diff,...,vol_3m_rank,vol_6m_rank,log_size_z,turnover_z,rev_1m_z,mom_6m_z,mom_12m_z,vol_3m_z,vol_6m_z,Target_z
64,2015-06-30,AU0000057408,Ordinary Shares,0.32,969193787.0,141701885.0,-0.085714,-0.085714,2022-02-28,30 days,...,0.289474,0.989247,-0.853921,1.241796,-0.044295,-0.363285,-1.397317,-0.668645,2.781321,-0.591698
65,2015-07-31,AU0000057408,Ordinary Shares,0.29,969193787.0,50601202.0,-0.093750,-0.093750,2022-02-28,31 days,...,0.343915,0.983784,-0.865093,0.291696,-0.470395,0.483817,-1.682058,-0.533137,2.604798,-0.034237
66,2015-08-31,AU0000057408,Ordinary Shares,0.27,969193787.0,56595316.0,-0.068966,-0.068966,2022-02-28,31 days,...,0.378947,0.697297,-0.825407,0.385545,-0.580549,-1.542239,-1.382734,-0.518887,0.352208,-0.575522
67,2015-09-30,AU0000057408,Ordinary Shares,0.25,969193787.0,102343915.0,-0.074074,-0.074074,2022-02-28,30 days,...,0.046875,0.162162,-0.864670,0.983566,-0.012135,-0.614043,-0.978676,-1.040613,-0.856908,-2.286811
68,2015-10-31,AU0000057408,Ordinary Shares,1.75,106611781.0,81356171.0,6.000000,-0.300000,2022-02-28,31 days,...,0.046392,0.196809,-1.050228,3.749652,-0.625132,-0.547221,-1.197268,-1.028051,-0.799505,-0.593642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110451,1999-08-31,USU872831040,Ordinary Shares,1.17,32762499.0,1764000.0,-0.558491,-0.558491,2000-01-31,31 days,...,0.844221,0.613065,-1.760785,0.183414,1.494423,-1.957426,-2.484492,1.025471,0.072315,0.010821
110452,1999-09-30,USU872831040,Ordinary Shares,1.15,32762499.0,2552000.0,-0.017094,-0.017094,2000-01-31,30 days,...,0.980296,0.846535,-1.736302,0.456384,-3.316398,-1.587288,-2.017034,2.597526,0.936546,-1.489651
110453,1999-10-31,USU872831040,Ordinary Shares,0.90,32762499.0,1536000.0,-0.217391,-0.217391,2000-01-31,31 days,...,0.979695,0.865285,-1.882837,0.270060,-0.012650,-2.440363,-2.227298,2.616222,1.070860,2.950557
110454,1999-11-30,USU872831040,Ordinary Shares,2.08,32762499.0,16148500.0,1.311111,1.311111,2000-01-31,30 days,...,0.913265,0.921875,-1.412876,4.143830,-1.521327,-2.251671,-1.661306,1.439622,1.430356,-2.864558
110455,1999-12-31,USU872831040,Ordinary Shares,0.70,32762499.0,26500000.0,-0.663462,-0.663462,2000-01-31,31 days,...,0.990050,0.989796,-2.134076,6.560437,2.878374,-2.009301,-1.723351,3.142531,3.213351,-2.882072

### 3. Merging "Best Ideas" data

In [63]:
import pandas as pd

# -------------------------------------------------------------------
# STEP 1: LOAD AND CLEAN THE MUTUAL FUND DATA
# -------------------------------------------------------------------
portfolios_df = pd.read_csv('../Data/portfolios_master_updated.csv')

# Drop any rows where the stock ISIN is missing (e.g., Cash or external bonds)
portfolios_df = portfolios_df.dropna(subset=['stock_isin']).copy()

# Align the portfolio dates to the End-of-Month to match your Master Equity Panel
portfolios_df['date'] = pd.to_datetime(portfolios_df['date']) + pd.offsets.MonthEnd(0)

# -------------------------------------------------------------------
# STEP 2: CALCULATE "BEST IDEAS" (TOP 10 CONVICTION)
# -------------------------------------------------------------------
# Rank the holdings within every single fund, every single month based on weight
portfolios_df['Fund_Rank'] = portfolios_df.groupby(['fund_name', 'date'])['weight'].rank(ascending=False, method='min')

# Create a binary flag: 1 if it is a Top 10 holding for that fund, 0 otherwise
portfolios_df['Is_Top_10'] = (portfolios_df['Fund_Rank'] <= 10).astype(int)

# -------------------------------------------------------------------
# STEP 3: AGGREGATE TO THE STOCK-MONTH LEVEL
# -------------------------------------------------------------------
# We group by ISIN and Date to see the overall "Smart Money" sentiment for each stock
bi_features = portfolios_df.groupby(['stock_isin', 'date']).agg(
    BI_Avg_Weight=('weight', 'mean'),        
    BI_Fund_Count=('fund_name', 'nunique'),  
    BI_Top10_Count=('Is_Top_10', 'sum')      
).reset_index()

# Sort to ensure chronological order before shifting
bi_features = bi_features.sort_values(['stock_isin', 'date'])

# THE FIX: Lag the Mutual Fund features by 1 month to account for reporting delays!
# We group by ISIN and shift the features forward by 1 row.
bi_features[['BI_Avg_Weight', 'BI_Fund_Count', 'BI_Top10_Count']] = bi_features.groupby('stock_isin')[['BI_Avg_Weight', 'BI_Fund_Count', 'BI_Top10_Count']].shift(1)

# Drop the NaNs created by the shift (the very first month a stock is held)
bi_features = bi_features.dropna()

# -------------------------------------------------------------------
# STEP 4: MERGE WITH YOUR POST-2010 INVESTABLE UNIVERSE
# -------------------------------------------------------------------
# Create the Modern Track (2010 onwards) from your clean equity dataframe
# (Assuming your clean df from the last step is named `equity_df_sorted`)
modern_equity_df = investable_universe[(investable_universe['TradeDate'] >= '2010-02-28') & (investable_universe['TradeDate'] <= '2024-12-31')].copy()

# Left merge the Best Ideas data onto the stock panel
modern_equity_df = pd.merge(
    modern_equity_df, 
    bi_features, 
    left_on=['ISIN', 'TradeDate'], 
    right_on=['stock_isin', 'date'], 
    how='left'
)

# -------------------------------------------------------------------
# STEP 5: FILL NaNs AND Z-SCORE THE SMART MONEY FEATURES
# -------------------------------------------------------------------
# If a stock is not held by ANY mutual fund, it gets a NaN from the merge.
# We must fill these with 0, because 0 funds = 0 weight, 0 count, 0 top 10s.
smart_money_cols = ['BI_Avg_Weight', 'BI_Fund_Count', 'BI_Top10_Count']
for col in smart_money_cols:
    modern_equity_df[col] = modern_equity_df[col].fillna(0)

# Finally, Cross-Sectionally Z-Score these new features just like Momentum!
# This ensures XGBoost compares "Fund Conviction" directly against "Momentum" on the exact same scale.
for col in smart_money_cols:
    modern_equity_df[f'{col}_z'] = modern_equity_df.groupby('TradeDate')[col].transform(lambda x: (x - x.mean()) / x.std())

# Clean up redundant columns from the merge
modern_equity_df = modern_equity_df.drop(columns=['stock_isin', 'date'])

print(f"Modern Dataset successfully created with shape: {modern_equity_df.shape}")
print("Smart Money factors engineered and Z-scored!")

Modern Dataset successfully created with shape: (34829, 48)
Smart Money factors engineered and Z-scored!

In [64]:
# save the final DataFrame to a new CSV file
modern_equity_df.to_csv('../Data/modern_equity_dataset.csv', index=False)

In [67]:
# check the date ranges of the final datasets
print("Date range of the original equity dataset:", modern_equity_df['TradeDate'].min(), "to", modern_equity_df['TradeDate'].max())
print("Date range of the investable universe:", investable_universe['TradeDate'].min(), "to", investable_universe['TradeDate'].max())

Date range of the original equity dataset: 2010-02-28 00:00:00 to 2024-12-31 00:00:00
Date range of the investable universe: 1981-01-31 00:00:00 to 2024-12-31 00:00:00